### ISSUE TITLE
"ffmpeg exited with code 1" after finding mp4 file

### ISSUE THREAD

**Issue by keith24** [thumbsup/thumbsup#104]
Found another one for you.  :smiley: 

## Bug report

Thumbsup version: 2.3.1
Node version: 10.2.1
NPM version: 6.1.0
Operating system: Ubuntu 16.04

```sh
$ thumbsup --input ~/photos --output /srv/pix
 
 ✔ Indexing folder
 ❯ Processing media (211/8741)
   ⠴ media/thumbs/2017/ecuador/DSCF1499.JPG
   ✖ media/large/2017/ecuador/DSCF1498.mp4
     → Error: Error: ffmpeg exited with code 1
   Creating website
 
Unexpected error Error: Error: Error: ffmpeg exited with code 1
    at job.task.then.catch.err (/home/keith/.nvm/versions/node/v10.2.1/lib/node_modules/thumbsup/node_modules/listr-work-queue/lib/index.js:50:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Setting `DEBUG` didn't help much:

```sh
$ DEBUG="*" thumbsup --input ~/photos --output /srv/pix
...
  thumbsup:debug Comparing unknown/goodwill/utah/1470267732.jpg (1470267769000) and media/large/unknown/goodwill/utah/1470267732.jpg (0) +1ms
  thumbsup:debug Comparing unknown/goodwill/utah/1470267732.jpg (1470267769000) and media/large/unknown/goodwill/utah/1470267732.jpg (0) +1ms
  thumbsup:info Calculated required tasks { sourceFiles: 4264, tasks: 8528 } +0ms
  thumbsup:debug photo:large from /home/keith/photos/2017/ecuador/DSCF1499.JPG to /srv/pix/media/large/2017/ecuador/DSCF1499.JPG +567ms
 ✔ Indexing folder
 ❯ Resizing media
   ⠇ media/large/2017/ecuador/DSCF1499.JPG
   ⠇ media/thumbs/2017/ecuador/DSCF1500.JPG
 ✔ Indexing folder
 ❯ Resizing media
 ✔ Indexing folder
 ❯ Processing media (1/8528)
 ✔ Indexing folder
 ✔ Indexing folder
 ✔ Indexing folder
 ❯ Processing media (3/8528)
   ⠸ media/thumbs/2017/ecuador/DSCF1501.jpg
   ⠸ media/large/2017/ecuador/DSCF1501.jpg
   Creating website
  thumbsup:trace ffmpeg exited with code 0 +0ms
 ✔ Indexing folder 
 ❯ Processing media (3/8528) 
 ✔ Indexing folder 
 ✔ Indexing folder 
 ❯ Processing media (4/8528) 
 ✔ Indexing folder 
 ❯ Processing media (5/8528) 
 ✔ Indexing folder 
 ✔ Indexing folder 
 ❯ Processing media (5/8528) 
   ⠸ media/thumbs/2017/ecuador/DSCF1502.JPG 
   ✖ media/large/2017/ecuador/DSCF1501.mp4 
     → Error: Error: ffmpeg exited with code 1 
   Creating website 
 
Unexpected error Error: Error: Error: ffmpeg exited with code 1 
    at job.task.then.catch.err (/home/keith/.nvm/versions/node/v10.2.1/lib/node_modules/thumbsup/node_modules/listr-work-queue/lib/index.js:50:14) 
    at process._tickCallback (internal/process/next_tick.js:68:7) 
```

**Comment by rprieto** [comment]
Hi, thank you for the report! Can you try `--log debug`, or even `--log trace`? What’s the length of the MP4 file?

I’m also working on error handling so a single error doesn’t stop the gallery from generating :smile:

**Comment by keith24** [comment]
I don't think the extra debugging is much help; it doesn't reveal the ffmpeg error: 

```sh
$ DEBUG="*" thumbsup --input ~/photos --output /srv/pix --log trace
...
  thumbsup:debug Comparing unknown/goodwill/utah/1470267732.jpg (1470267769000) and media/large/unknown/goodwill/utah/1470267732.jpg (1528270473031) +0
ms
  thumbsup:debug Comparing unknown/goodwill/utah/1470267732.jpg (1470267769000) and media/large/unknown/goodwill/utah/1470267732.jpg (1528270473031) +0
ms
  thumbsup:info Calculated required tasks { sourceFiles: 3, tasks: 3 } +0ms
  thumbsup:info Waiting [started] +2m
  thumbsup:info Waiting [started] +0ms
  thumbsup:info Finished [title changed] +2ms
  thumbsup:info media/large/2017/ecuador/DSCF1346.mp4 [title changed] +1ms
  thumbsup:debug video:resized from /home/keith/photos/2017/ecuador/DSCF1346.MOV to /srv/pix/media/large/2017/ecuador/DSCF1346.mp4 +27ms
  thumbsup:info Finished [title changed] +84ms
  thumbsup:info media/large/2017/ecuador/DSCF1498.mp4 [title changed] +0ms
  thumbsup:debug video:resized from /home/keith/photos/2017/ecuador/DSCF1498.MOV to /srv/pix/media/large/2017/ecuador/DSCF1498.mp4 +102ms
  thumbsup:trace ffmpeg exited with code 1 +0ms
  thumbsup:info media/large/2017/ecuador/DSCF1346.mp4 [failed] +6s
  thumbsup:info → Error: Error: ffmpeg exited with code 1 +2ms
  thumbsup:info Resizing media [failed] +2ms
  thumbsup:info → Error: Error: ffmpeg exited with code 1 +1ms
  thumbsup:error 
  thumbsup:error Unexpected error Error: Error: Error: ffmpeg exited with code 1
    at job.task.then.catch.err (/home/keith/.nvm/versions/node/v10.2.1/lib/node_modules/thumbsup/node_modules/listr-work-queue/lib/index.js:50:14)
    at process._tickCallback (internal/process/next_tick.js:68:7) +0ms
```

But, I do now realize that the files were originally quicktime MOVs, not MP4s.  It seems like they sometimes pass, but sometimes the error is thrown.  

The input files are various sizes:

```sh
$ ll /home/keith/photos/2017/ecuador/*.MOV                                                                                       
-rw-rw-r-- 1 keith keith  32M Oct 15  2017 /home/keith/photos/2017/ecuador/DSCF1346.MOV
-rw-rw-r-- 1 keith keith  16M Nov  2  2017 /home/keith/photos/2017/ecuador/DSCF1498.MOV
-rw-rw-r-- 1 keith keith 6.2M Nov  2  2017 /home/keith/photos/2017/ecuador/DSCF1501.MOV
```

The output files are empty: 
```sh$ ll /srv/pix/media/large/2017/ecuador/*.mp4
-rw-rw-r-- 1 keith keith 0 Jun  7 01:42 /srv/pix/media/large/2017/ecuador/DSCF1346.mp4
-rw-rw-r-- 1 keith keith 0 Jun  7 01:42 /srv/pix/media/large/2017/ecuador/DSCF1498.mp4
```

**Comment by rprieto** [comment]
I had a look at the full `ffmpeg` output, and it doesn't print much when processing an invalid movie. The most we could get is something like `Invalid data found when processing input` which is not much better than `ffmpeg exited with code 1`.

Since the new version prints a summary + logs the full ffmpeg command, I might close this issue for now. Let me know if you can think of anything else to make troubleshooting better. Thanks for the bug report!
