### ISSUE TITLE
Cannot find module 'listr-work-queue'

### ISSUE THREAD

**Issue by zbacsi** [thumbsup/thumbsup#113]
module.js:544
    throw err;
    ^

Error: Cannot find module 'listr-work-queue'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/node_modules/thumbsup/src/steps/step-process.js:6:24)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)

@thumbsup/listr-work-queue@1.0.0 requires a peer of listr@^0.13.0 but none is installed. You must install peer dependencies yourself.

```
Thumbsup version: 2.4.0
Node version: 9.2.0
NPM version: 6.1.0
Operating system: Ubuntu Linux 16.04.4 LTS
```

**Comment by zbacsi** [comment]
After a deep analysis I found the @thumbsup/listr-work-queue was installed in a wrong directory:

node_modules/thumbsup/node_modules/@thumbsup/list-work-queue

I moved it to one folder up, and it's work fine.

**Comment by rprieto** [comment]
This should be fixed now. Thanks for your patience!
