### ISSUE TITLE
Error: Invalid JSON (Unexpected "\u001b"

### ISSUE THREAD

**Issue by dzhus** [thumbsup/thumbsup#135]
## Bug report

If running as a Docker container:

```
Thumbsup image tag: thumbsupgallery/thumbsup:2.4.2@sha256:4ae99db31ef0b6a321d1ee4ac55428aa8c567bd7fa96d1d6886f7376e521695f
Docker version: 18.06.1-ce
Operating system: macOS High Sierra 10.13.6 (17G2307)
```

About the bug...

Running the command

```
docker run -e DEBUG="*" -t                -v `pwd`:/work             -u $(id -u):$(id -g)       thumbsupgallery/thumbsup   thumbsup --input /work/media --output /work/gallery --theme mosaic
```

I'm getting the error message:

```
 ⠴ Indexing folder
   → Indexing 15/495 (3%)
   Resizing media
   Creating website

Unexpected error Invalid JSON (Unexpected "\u001b" at position 0 in state STOP)
```

`thumbsup.log` contents:

```
2018-11-03T09:27:05.869Z thumbsup:error Error: Invalid JSON (Unexpected "\u001b" at position 0 in state STOP)
2018-11-03T09:27:05.869Z thumbsup:error     at Parser.proto.charError (/thumbsup/node_modules/jsonparse/jsonparse.js:90:16)
2018-11-03T09:27:05.869Z thumbsup:error     at Parser.proto.write (/thumbsup/node_modules/jsonparse/jsonparse.js:154:23)
2018-11-03T09:27:05.869Z thumbsup:error     at Stream.<anonymous> (/thumbsup/node_modules/JSONStream/index.js:21:12)
2018-11-03T09:27:05.869Z thumbsup:error     at Stream.stream.write (/thumbsup/node_modules/through/index.js:26:11)
2018-11-03T09:27:05.869Z thumbsup:error     at DestroyableTransform.ondata (/thumbsup/node_modules/readable-stream/lib/_stream_readable.js:619:20)
2018-11-03T09:27:05.869Z thumbsup:error     at emitOne (events.js:116:13)
2018-11-03T09:27:05.869Z thumbsup:error     at DestroyableTransform.emit (events.js:211:7)
2018-11-03T09:27:05.869Z thumbsup:error     at addChunk (/thumbsup/node_modules/readable-stream/lib/_stream_readable.js:291:12)
2018-11-03T09:27:05.869Z thumbsup:error     at readableAddChunk (/thumbsup/node_modules/readable-stream/lib/_stream_readable.js:278:11)
2018-11-03T09:27:05.869Z thumbsup:error     at DestroyableTransform.Readable.push (/thumbsup/node_modules/readable-stream/lib/_stream_readable.js:245:10)
```

I tried enabling `--log trace` but there're still no pointers as to which file does actually cause the error.

**Comment by rprieto** [comment]
Hi, thanks for reporting the issue. I'll see what I can do to print the name of the file causing issues. Are you OK to make changes to the thumbsup code locally to speed things up?

**Comment by dzhus** [comment]
@rprieto Sure

**Comment by rprieto** [comment]
Can you please try the following

```bash
cd test
mkdir test
npm init
npm install thumbsup
```

Then replace the contents of `src/components/exiftool/stream.js` with
https://gist.github.com/rprieto/d4ddf27e8c8ab872603ab48e3d13fcc4. The main change is line 46-52 to capture more detail while parsing the EXIF data stream.

And finally run thumbsup using `node node_modules/thumbsup/bin/thumbsup.js --input /path/to/your/photos --output tmp --log debug`. It should print the chunk of EXIF data that contained the invalid character.

It's your EXIF data so please feel free to share as little or a much as you want. Hopefully something odd stands out!

**Comment by rprieto** [comment]
That's very strange. 

- Does it mean that this time it went past the "updating database phase"? You can try deleting the `thumbsup.db` file to reindex.
- I updated the gist with a small logging change, do you mind trying again?
- As a side note I should update the docs, `concurrency` is usually not worth setting over the CPU core/thread count

**Comment by dzhus** [comment]
Looks like both problems are caused by files with leading dashes in filenames, as in:

```
  -rw-r--r--  1 dmitry.dzhus  staff     285374  1 Nov 16:00 --_963137132_o.jpg
  -rw-r--r--  1 dmitry.dzhus  staff     615594  1 Nov 16:07 -11_6967889950_o.jpg
  -rw-r--r--  1 dmitry.dzhus  staff     280764  1 Nov 16:01 -1939_2576736711_o.jpg
  -rw-r--r--  1 dmitry.dzhus  staff     474316  1 Nov 16:02 -27_2741667805_o.jpg
```

I renamed the files and it works as expected, both using Docker image and running thumbsup directly.

**Comment by rprieto** [comment]
That's very interesting thanks. Nice troubleshooting :100: I'll see if I can add test cases around that. Are they regular ASCII dashes, or en/em-dashes?

**Comment by dzhus** [comment]
They are regular dashes. My Flickr takeaway archive seems to contain many such files. They try to prepend the filename with the photo title (as in `photo-title-382910389201_o.jpg`) but only Latin characters are included. So if the photo title is all non-Latin (Cyrillic in my case) the dash is left dangling at the beginning of the filename :) 

Thank you for thumbsup :thumbsup:

**Comment by rprieto** [comment]
As an update, ExifTool cannot directly process files that start with a dash (see http://u88.n24.queensu.ca/exiftool/forum/index.php?topic=3683.0) as it tries to interpret them as command-line args. This might or might not be the cause of the issue. I'm adding some test cases around that and will hopefully have a fix so that they get processed as expected.
