### ISSUE TITLE
Error relocating sqlite node on latest docker

### ISSUE THREAD

**Issue by pmow** [thumbsup/thumbsup#175]
```
Thumbsup image tag: default (latest)
Docker version: 18.09.6
Operating system: Ubuntu 18.04.2 LTS
```

About the bug...

- Are you getting an error message?
```internal/modules/cjs/loader.js:805
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Error relocating /thumbsup/node_modules/better-sqlite3/build/better_sqlite3.node: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorE: symbol not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:805:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/thumbsup/node_modules/better-sqlite3/lib/database.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

- Have you tried running `DEBUG="*" thumbsup <args>` to get more troubleshooting info?
Yes, it produces no new info.

- Is the behavior different from expected?
Yes, I've previously run it just fine.

- Can you provide steps to reproduce the issue?
Starting with 2.11.0, this error appears.  I'm using the following command:
```docker run  \
-v '/mnt/media2/Photos.Final':'/working' \
--rm -u 1000:1004 \
thumbsupgallery/thumbsup \
thumbsup --input /working/originals --output /working/gallery --photo-download copy --cleanup --concurrency 12 \
--sort-albums-direction desc \
--sort-albums-by title \
--theme cards \
--name thumbsup-temp \
--title "pmow's photos"

**Comment by rprieto** [comment]
Thanks for your detailed report! This definitely a bug, I'll look into it. Can you stay on the previous image for now?

**Comment by rprieto** [comment]
Hi, I got to the bottom of it and pushed a new image as `thumbsupgallery/thumbsup:2.11.0`. Thanks again for bringing it up, and let me know if you still have the issue.
