### ISSUE TITLE
Error write EIO at afterWriteDispatch

### ISSUE THREAD

**Issue by GlenHertz** [thumbsup/thumbsup#191]
## Bug report

I have thumbsup setup in a FreeBSD jail and has been working fined for many weeks.  Today I imported more photos and then ran `nohup index_photos`, where `index_photos` is a script:
```
#!/bin/sh
thumbsup --config config.json
```

Near the end of thumbsup running I get the error

```
2020-03-25T05:53:44.851Z thumbsup:info \xe2\x94\x82  Gallery generated successfully!       \xe2\x94\x82
2020-03-25T05:53:44.851Z thumbsup:info \xe2\x94\x82  90 albums, 36953 photos, 5202 videos  \xe2\x94\x82
2020-03-25T05:53:44.851Z thumbsup:info \xe2\x94\x82                                        \xe2\x94\x82
2020-03-25T05:53:44.851Z thumbsup:info \xe2\x94\x94\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80
\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe
2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x
94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\x80\xe2\x94\
x98
2020-03-25T05:53:44.851Z thumbsup:info
2020-03-25T05:53:44.915Z thumbsup:error Error: write EIO
2020-03-25T05:53:44.915Z thumbsup:error     at afterWriteDispatched (internal/stream_base_commons.js:153:25)
2020-03-25T05:53:44.915Z thumbsup:error     at writeGeneric (internal/stream_base_commons.js:144:3)
2020-03-25T05:53:44.915Z thumbsup:error     at WriteStream.Socket._writeGeneric (net.js:778:11)
2020-03-25T05:53:44.915Z thumbsup:error     at WriteStream.Socket._write (net.js:790:8)
2020-03-25T05:53:44.915Z thumbsup:error     at doWrite (_stream_writable.js:461:12)
2020-03-25T05:53:44.915Z thumbsup:error     at writeOrBuffer (_stream_writable.js:443:5)
2020-03-25T05:53:44.915Z thumbsup:error     at WriteStream.Writable.write (_stream_writable.js:323:11)
2020-03-25T05:53:44.915Z thumbsup:error     at Object.exports.show (/usr/local/lib/node_modules/thumbsup/node_modules/cli-cursor/index.
js:14:4)
2020-03-25T05:53:44.915Z thumbsup:error     at VerboseRenderer.end (/usr/local/lib/node_modules/thumbsup/node_modules/listr-verbose-ren
derer/index.js:60:13)
2020-03-25T05:53:44.915Z thumbsup:error     at /usr/local/lib/node_modules/thumbsup/node_modules/listr/index.js:107:20
2020-03-25T05:53:44.916Z thumbsup:error
2020-03-25T05:53:44.916Z thumbsup:error Unexpected error write EIO
2020-03-25T05:53:44.918Z thumbsup:error
```

```
Thumbsup version: 2.12.0
Node version: v13.3.0
NPM version: 6.12.1
Operating system: FreeBSD 11.2-STABLE (jail)
```

I'll try another run with DEBUG to see if it reports any other info.

**Comment by rprieto** [comment]
Hi, thanks for hte bug report. It seems that it prints the error at the very end. Can you confirm if everything generated fine?

This looks like quite a low-level error in https://github.com/SamVerschueren/listr-verbose-renderer which is responsible for printing the progress. The only references to `Unexpected error write EIO` I can find are about actual I/O errors, or display errors on Windows when the wrong `code page` is used. I know you're running BSD, but any chance something has changed disk or display wise?

**Comment by rprieto** [comment]
Hi @GlenHertz. Are you still experiencing this problem? Otherwise I will close this issue. Thanks
