### ISSUE TITLE
Can not run

### ISSUE THREAD

**Issue by DefectingCat** [thumbsup/thumbsup#203]
i used npm to installed:
```
npm install -g thumbsup
```
and the dependencies all installed.

```
exiftool: 12.02
Thumbsup version: 2.14.0
Node version: v14.5.0
NPM version: 6.14.6
Operating system: arch linux
```
So. i use the quick start run it : 
```
thumbsup --input photo --output web
```

get the some error:

```
xfy@t450s : ~/Documents/Github
[0] % thumbsup --input photo --output web

/home/xfy/Documents/Github/thumbsup/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/build/better_sqlite3.node
 → /home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/compiled/14.5.0/linux/x64/better_sqlite3.node
 → /home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/lib/binding/node-v83-linux-x64/better_sqlite3.node
    at bindings (/home/xfy/Documents/Github/thumbsup/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/lib/index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:1201:30) {
  tries: [
    '/home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/build/better_sqlite3.node',
    '/home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/build/Debug/better_sqlite3.node',
    '/home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/build/Release/better_sqlite3.node',
    '/home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/out/Debug/better_sqlite3.node',
    '/home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/Debug/better_sqlite3.node',
    '/home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/out/Release/better_sqlite3.node',
    '/home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/Release/better_sqlite3.node',
    '/home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/build/default/better_sqlite3.node',
    '/home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/compiled/14.5.0/linux/x64/better_sqlite3.node',
    '/home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node',
    '/home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node',
    '/home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node',
    '/home/xfy/Documents/Github/thumbsup/node_modules/better-sqlite3/lib/binding/node-v83-linux-x64/better_sqlite3.node'
  ]
}
```

**Comment by rprieto** [comment]
Hi, thanks for reporting this. It seems to be a problem with `better-sqlite3`. I have never tried on Node 14, is it possible for you to test on Node 10 or 12?

**Comment by rprieto** [comment]
Thank you. After switching version, did you reinstall node_modules ? These are binary (compiled) modules so I suspect they need a fresh `rm -rf node_modules && npm install`.

**Comment by rprieto** [comment]
Hi, without any updates I'm closing this issue for now. Please re-open it if it's still an issue.
