### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by gebailey** [thumbsup/thumbsup#226]
## Bug report

```
Thumbsup image tag: `thumbsupgallery/thumbsup:2.14.0`
Docker version: `Docker version 19.03.13-ce, build 4484c46`
Operating system: `Amazon Linux release 2 (Karoo)`
```

Running with `--log debug` against directory tree of approx. 35K images, and get the following error at (or near) the end of the indexing process:

```
  thumbsup:info → Indexing 34034/35452 (96%) +4s
  thumbsup:info → Indexing 34389/35452 (97%) +3s
  thumbsup:debug Exiftool exited with code 0 +28s
  thumbsup:info → Indexing 34743/35452 (98%) +4s
  thumbsup:info → Indexing 35098/35452 (99%) +6s
  thumbsup:info → Indexing 35452/35452 (100%) +5s
  thumbsup:error TypeError: Cannot read property 'indexOf' of undefined
  thumbsup:error     at dimensions (/thumbsup/node_modules/thumbsup/src/model/metadata.js:143:20)
  thumbsup:error     at new Metadata (/thumbsup/node_modules/thumbsup/src/model/metadata.js:33:18)
  thumbsup:error     at EventEmitter.emitter.on.file (/thumbsup/node_modules/thumbsup/src/steps/step-index.js:42:20)
  thumbsup:error     at EventEmitter.emit (events.js:198:13)
  thumbsup:error     at Stream.finished (/thumbsup/node_modules/thumbsup/src/components/index/index.js:44:17)
  thumbsup:error     at Stream.emit (events.js:198:13)
  thumbsup:error     at Stream.<anonymous> (/thumbsup/node_modules/event-stream/index.js:51:18)
  thumbsup:error     at Stream.emit (events.js:203:15)
  thumbsup:error     at Stream.handleEnd (/thumbsup/node_modules/duplexer/index.js:81:21)
  thumbsup:error     at Stream.emit (events.js:203:15) +0ms
  thumbsup:error 
  thumbsup:error Unexpected error Cannot read property 'indexOf' of undefined +0ms
  thumbsup:error 
  thumbsup:error ┌───────────────────────────────────────────────────────────────────────────┐
  thumbsup:error │                                                                           │
  thumbsup:error │  Something went wrong!                                                    │
  thumbsup:error │                                                                           │
  thumbsup:error │  An unexpected error occurred and the gallery didn't build successfully.  │
  thumbsup:error │  This is most likely an edge-case that hasn't been tested before.         │
  thumbsup:error │                                                                           │
  thumbsup:error │  Please check thumbsup.log in the output folder.                          │
  thumbsup:error │  To help improve thumbsup and hopefully resolve your problem,             │
  thumbsup:error │  you can raise an issue at https://github.com/thumbsup/thumbsup/issues.   │
  thumbsup:error │                                                                           │
  thumbsup:error └───────────────────────────────────────────────────────────────────────────┘
  thumbsup:error  +0ms
  thumbsup:debug Exiftool exited with code 0 +16s
```

**Comment by gebailey** [comment]
I tracked this down to a couple of (apparently corrupted) JPG files.  The "Composite" field of the EXIF data has:

**Comment by rprieto** [comment]
Hi, thank you for tracking down the problem. I just added a fix to gracefully handle files with missing `Composite.ImageSize`. 

I agree it would be good to log & skip invalid files. I'll have a look at what's possible.
