### ISSUE TITLE
better_sqlite3.node was compiled against a different Node.js version

### ISSUE THREAD

**Issue by ochompsky** [thumbsup/thumbsup#232]
Running OSX 11.1.  I've used thumbsup many times before without issue but now im getting this:  

```
Error: The module '/usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 88. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1167:18)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at bindings (/usr/local/lib/node_modules/thumbsup/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/local/lib/node_modules/thumbsup/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by rprieto** [comment]
Hi, did you upgrade from Node 14 to Node 15? If so you need to run `npm rebuild` in the thumbsup folder (if you run from , or simply rerun `npm install thumbsup`.

**Comment by rprieto** [comment]
Hi, did you upgrade from Node 14 to Node 15? If so you need to run `npm install thumbsup` again to ensure dependencies are re-built if needed.

**Comment by rprieto** [comment]
Hi @ochompsky. I'm closing this as it should be resolved. Please re-open it if the issue persists.
