### ISSUE TITLE
Docker image does not support zip

### ISSUE THREAD

**Issue by domenecsos** [thumbsup/thumbsup#289]
## Bug description

When requested to create a zip file, docker image fails at the zip stage

## Steps to reproduce

Run with `--album-zip-files=true"`, it fails and the log states
```
2022-04-18T13:37:06.479Z thumbsup:warn dcraw (https://www.cybercom.net/~dcoffin/dcraw/) is not installed. You will not be able to process RAW photos.
2022-04-18T13:48:08.300Z thumbsup:error Error: please verify that <zip> is installed on your system
2022-04-18T13:48:08.315Z thumbsup:error Error: spawn zip ENOENT
2022-04-18T13:48:08.379Z thumbsup:error Error: Error creating ZIP file /output/06Santos_MariaDeLaRosa.zip
2022-04-18T13:48:08.379Z thumbsup:error     at ChildProcess.child.on (/thumbsup/node_modules/thumbsup/src/steps/step-album-zip.js:54:30)
2022-04-18T13:48:08.379Z thumbsup:error     at ChildProcess.emit (events.js:198:13)
2022-04-18T13:48:08.379Z thumbsup:error     at maybeClose (internal/child_process.js:982:16)
2022-04-18T13:48:08.379Z thumbsup:error     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2022-04-18T13:48:08.379Z thumbsup:error     at onErrorNT (internal/child_process.js:415:16)
2022-04-18T13:48:08.379Z thumbsup:error     at process._tickCallback (internal/process/next_tick.js:63:19)
```

I then `sh`'ed into a running container and found that there is no support for zip.

```
admin@nasdsv01:/$ sudo docker ps
CONTAINER ID   IMAGE                      COMMAND                  CREATED              STATUS          PORTS     NAMES
f8aa0e989f73   thumbsupgallery/thumbsup   "tini -g -- thumbsup…"   About a minute ago   Up 59 seconds             goofy_lederberg

admin@nasdsv01:/$ sudo docker exec -it goofy_lederberg /bin/sh
/ # zip
/bin/sh: zip: not found
```

To be noted, I am running it on a Synology NAS which has some sort of particular management of Docker images.

**Comment by domenecsos** [comment]
An image with zip installed worked properly, except that the generated zips had 000 mask, no permissions at all.

```
# syntax=docker/dockerfile:1
FROM thumbsupgallery/thumbsup
RUN apk add --no-cache zip
```
