### ISSUE TITLE
Broken on MacOS Ventura

### ISSUE THREAD

**Issue by chaosarium** [thumbsup/thumbsup#322]
## Bug description

```
❯ thumbsup --input ./input --output ./out --log debug

/usr/local/lib/node_modules/thumbsup/node_modules/macos-release/index.js:27
        const [name, version] = nameMap.get(release);
                                ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at macosRelease (/usr/local/lib/node_modules/thumbsup/node_modules/macos-release/index.js:27:26)
    at osName (/usr/local/lib/node_modules/thumbsup/node_modules/os-name/index.js:21:18)
    at new Insight (/usr/local/lib/node_modules/thumbsup/node_modules/insight/lib/index.js:37:13)
    at new Analytics (/usr/local/lib/node_modules/thumbsup/bin/analytics.js:11:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/thumbsup/bin/thumbsup.js:28:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
```

## Steps to reproduce

1. Update to MacOS Ventura (13)
2. Attempt to run thumbsup --input ./input --output ./out

## Potential fix

In `node_modules/thumbsup/node_modules/macos-release/index.js:27`, adding the line `[22, ['Ventura', '13']],` to before `[21, ['Monterey', '12']],` temporarily fixes the issue

**Comment by aellwein** [comment]
Had a same issue today.
@rprieto why is this ``macos-release`` package needed anyway? It always breaks things up with every major MacOS release cause ``thumbsup`` always needs to keep it current.

**Comment by rprieto** [comment]
Hi, thanks for raising this. Unfortunately `macos-release` is not a direct dependency, it’s quite deep in the chain.

I see the package itself now supports Ventura, I will try updating all dependencies to see if the latest version is pulled down.

**Comment by rprieto** [comment]
This dependency is coming from the `insight` package, which is used to report optional & anonymous usage metrics (OS version, Gallery size...). I will raise an issue on `insight`. If this doesn't work I'll have to consider dropping the metrics, although it's been useful to understand what use-cases to focus on.

**Comment by aellwein** [comment]
@rprieto thank you!

**Comment by mischah** [comment]
Here is the upstream issue in case someone wants to fix this:
https://github.com/yeoman/insight/issues/83

**Comment by rprieto** [comment]
For now I have removed usage stats from thumbsup.
We can re-introduce them again if needed in the future.
