### ISSUE TITLE
Unexpected error Cannot read properties of undefined (reading 'FileModifyDate')

### ISSUE THREAD

**Issue by inhahe** [thumbsup/thumbsup#342]
## Bug description

 GNU nano 7.2                                                                   thumbsup.log                                                                             
2023-05-31T02:20:38.800Z thumbsup:warn dcraw (https://www.cybercom.net/~dcoffin/dcraw/) is not installed. You will not be able to process RAW photos.
2023-05-31T02:20:41.219Z thumbsup:error TypeError: Cannot read properties of undefined (reading 'FileModifyDate')
2023-05-31T02:20:41.219Z thumbsup:error     at Stream.<anonymous> (/thumbsup/node_modules/thumbsup/src/components/index/index.js:85:45)
2023-05-31T02:20:41.219Z thumbsup:error     at Stream.emit (node:events:513:28)
2023-05-31T02:20:41.219Z thumbsup:error     at stream.write (/thumbsup/node_modules/event-stream/index.js:61:10)
2023-05-31T02:20:41.219Z thumbsup:error     at Stream.ondata (node:internal/streams/legacy:20:31)
2023-05-31T02:20:41.219Z thumbsup:error     at Stream.emit (node:events:513:28)
2023-05-31T02:20:41.219Z thumbsup:error     at Stream.reemit (/thumbsup/node_modules/duplexer/index.js:70:25)
2023-05-31T02:20:41.219Z thumbsup:error     at Stream.emit (node:events:513:28)
2023-05-31T02:20:41.219Z thumbsup:error     at drain (/thumbsup/node_modules/through/index.js:36:16)
2023-05-31T02:20:41.219Z thumbsup:error     at stream.queue.stream.push (/thumbsup/node_modules/through/index.js:45:5)
2023-05-31T02:20:41.219Z thumbsup:error     at parser.onValue (/thumbsup/node_modules/JSONStream/index.js:118:16)

## Steps to reproduce

I followed the instructions for running the docker image at https://thumbsup.github.io/docs/2-installation/docker/.

sudo docker run -t -v "$(pwd):/home/inhahe/" -u $(id -u):$(id -g) ghcr.io/thumbsup/thumbsup thumbsup --input /home/inhahe/pics --output /home/inhahe/pics2

**Comment by inhahe** [comment]
Update: I tried leaving just *one*  file in pics, and I got this error:

```
2023-05-31T14:05:53.564Z thumbsup:warn gifsicle (http://www.lcdf.org/gifsicle) is not installed. You will not be able to process animated GIFs.
2023-05-31T14:05:54.452Z thumbsup:error Error: Invalid JSON (Unexpected "N" at position 0 in state STOP)
2023-05-31T14:05:54.452Z thumbsup:error     at proto.charError (/home/linuxbrew/.linuxbrew/lib/node_modules/thumbsup/node_modules/jsonparse/jsonparse.js:90:16)
2023-05-31T14:05:54.452Z thumbsup:error     at proto.write (/home/linuxbrew/.linuxbrew/lib/node_modules/thumbsup/node_modules/jsonparse/jsonparse.js:154:23)
2023-05-31T14:05:54.452Z thumbsup:error     at Stream.<anonymous> (/home/linuxbrew/.linuxbrew/lib/node_modules/thumbsup/node_modules/JSONStream/index.js:23:12)
2023-05-31T14:05:54.452Z thumbsup:error     at stream.write (/home/linuxbrew/.linuxbrew/lib/node_modules/thumbsup/node_modules/through/index.js:26:11)
2023-05-31T14:05:54.452Z thumbsup:error     at Transform.ondata (/home/linuxbrew/.linuxbrew/lib/node_modules/thumbsup/node_modules/readable-stream/lib/_stream_readable.js:629:20)
2023-05-31T14:05:54.452Z thumbsup:error     at Transform.emit (node:events:511:28)
2023-05-31T14:05:54.452Z thumbsup:error     at addChunk (/home/linuxbrew/.linuxbrew/lib/node_modules/thumbsup/node_modules/readable-stream/lib/_stream_readable.js:279:12)
2023-05-31T14:05:54.452Z thumbsup:error     at readableAddChunk (/home/linuxbrew/.linuxbrew/lib/node_modules/thumbsup/node_modules/readable-stream/lib/_stream_readable.js:262:11)
2023-05-31T14:05:54.452Z thumbsup:error     at Readable.push (/home/linuxbrew/.linuxbrew/lib/node_modules/thumbsup/node_modules/readable-stream/lib/_stream_readable.js:228:10)
2023-05-31T14:05:54.452Z thumbsup:error     at Transform.push (/home/linuxbrew/.linuxbrew/lib/node_modules/thumbsup/node_modules/readable-stream/lib/_stream_transform.js:132:32)

```

My only guess is that I'm getting three different kinds of failure modes depending on which file it comes across first. I'm guessing it's because of the filenames, which are coming from Windows. The one pic I left in pics this time has the name `#41 Roomba Led Long Exposure.jpg`.

**Comment by inhahe** [comment]
Update: I renamed `#41 Roomba Led Long Exposure.jpg` to `41 Roomba Led Long Exposure.jpg`, and it worked with only that single file in the pics directory.

**Comment by inhahe** [comment]
So I did `detox -r /home/inhahe/pics` and that solved the problem. But now I have a new problem. I'll add another issue.

**Comment by rprieto** [comment]
Hi @inhahe, thanks for your troubleshooting and for reporting this.
I think there might be multiple issues at play here.

Regarding the # character it seems that:
- exiftool will ignore any file paths starting with # (maybe because it thinks it's a comment, or maybe due to the way it parses its input on `stdin`).
- if this was the only file, then it thinks you didn't pass anything and prints an error message on `stdout`. Because we normally expect JSON this crashes the parser.

I can reproduce this with:

| Command | Description | Result |
|---|---|---|
| Normal file | `echo 'a.jpg' \| exiftool -@ -` | OK |
| File starting with # | `echo '#a.jpg' \| exiftool -@ -` | Error |

In any case this is an issue, because even if it's **not** the only file it would get ignored.
I will look into the right syntax for exiftool to accept them.

Regarding the other issues, were they also solved by running `detox`?

**Comment by inhahe** [comment]
Yes, using detox solves my problems. 

It seems without using detox, there are at least three different kinds of errors I get as a result of three different possibilities in filenames. One is spaces, I forget what the other ones are (I guess one was the # symbol). 

It seems it would be more ideal if it weren't necessary to use detox to fix all the filenames before running thumbsup. And as it is I have to keep copies of all my pic directories that I want to put on the web, and every time I save a new pic in one of those directories I have to save it in two places, because I store my pics on Windows, and every now and then I rsync them to my Linux VM to run thumbsup on them, and I don't want to run detox on my main Windows directories, but if I just rsynced them to Linux where I run detox on the directories, then it would re-add all the filenames that are different from their detoxed names, so I have to have copies of them all in directories on Windows that I detox every time I update my web pics. So that's four copies of my pics in total that I have to store on my PC: my main Windows directories, my detoxed Windows directories for the web, my detoxed Linux directory to use as the source for the thumbsup command (since it doesn't seem to work if I try to run it directly on my mounted Windows directory for some reason), and the destination directory for Thumbsup.
