### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by inhahe** [thumbsup/thumbsup#347]
## Steps to reproduce

I started to run thumbsup, then realized I forgot to do something first, so I aborted it while it was in the indexing phase. Then when I tried running it again I got a "database is locked" error.

Here's the log:
023-07-03T10:04:23.954Z thumbsup:error SqliteError: database is locked
2023-07-03T10:04:23.954Z thumbsup:error     at Database.exec (/home/linuxbrew/.linuxbrew/lib/node_modules/thumbsup/node_modules/better-sqlite3/lib/methods/wrappers.js:9:14)
2023-07-03T10:04:23.954Z thumbsup:error     at new Index (/home/linuxbrew/.linuxbrew/lib/node_modules/thumbsup/src/components/index/index.js:18:13)
2023-07-03T10:04:23.954Z thumbsup:error     at /home/linuxbrew/.linuxbrew/lib/node_modules/thumbsup/src/steps/step-index.js:21:19
2023-07-03T10:04:23.954Z thumbsup:error     at new Subscription (/home/linuxbrew/.linuxbrew/lib/node_modules/thumbsup/node_modules/zen-observable/lib/Observable.js:191:34)
2023-07-03T10:04:23.954Z thumbsup:error     at Observable.subscribe (/home/linuxbrew/.linuxbrew/lib/node_modules/thumbsup/node_modules/zen-observable/lib/Observable.js:228:12)
2023-07-03T10:04:23.954Z thumbsup:error     at /home/linuxbrew/.linuxbrew/lib/node_modules/thumbsup/node_modules/listr/lib/task.js:130:13
2023-07-03T10:04:23.954Z thumbsup:error     at new Promise (<anonymous>)
2023-07-03T10:04:23.954Z thumbsup:error     at handleResult (/home/linuxbrew/.linuxbrew/lib/node_modules/thumbsup/node_modules/listr/lib/task.js:129:14)
2023-07-03T10:04:23.954Z thumbsup:error     at /home/linuxbrew/.linuxbrew/lib/node_modules/thumbsup/node_modules/listr/lib/task.js:167:12
2023-07-03T10:04:23.954Z thumbsup:error     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by inhahe** [comment]
I rebooted Linux and it wasn't locked anymore.

**Comment by rprieto** [comment]
Thanks for reporting this, I will add documentation on how to unlock the database if this happens.

**Comment by inhahe** [comment]
I just got the 'database is locked' error again, is it in the documentation? If it is, where can I find it?
