### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by inhahe** [thumbsup/thumbsup#365]
## Steps to reproduce

I just installed thumbsup and all its dependencies on a new Linux Mint VM. I tried to run thumbsup and I got this error:

```
usr/local/lib/node_modules/thumbsup/node_modules/ini/lib/ini.js:140
      duplicates[keyRaw] = (duplicates?.[keyRaw] || 0) + 1
                                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/thumbsup/src/input/picasa.js:7:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

My node.js version is v12.22.9.

**Comment by inhahe** [comment]
Oh, I see that that wasn't the latest version of node. I don't know why it installed an old version, and even replied that it was the latest version when I tried to upgrade. I ended up having to install nvm and then use that to install node.

**Comment by rprieto** [comment]
Hi, glad you solved the issue. Node v12 has been out of support for a few years. I agree it's very strange it was the default installation.
