### ISSUE TITLE
Unexpected error Cannot read properties of undefined (reading 'FileModifyDate')

### ISSUE THREAD

**Issue by inhahe** [thumbsup/thumbsup#370]
## Steps to reproduce

```
2024-06-12T01:07:52.643Z thumbsup:warn dcraw (https://www.cybercom.net/~dcoffin/dcraw/) is not installed. You will not be able to process RAW photos.
2024-06-12T01:15:10.240Z thumbsup:error TypeError: Cannot read properties of undefined (reading 'FileModifyDate')
2024-06-12T01:15:10.240Z thumbsup:error     at Stream.<anonymous> (/usr/local/lib/node_modules/thumbsup/src/components/index/index.js:86:45)
2024-06-12T01:15:10.240Z thumbsup:error     at Stream.emit (node:events:512:28)
2024-06-12T01:15:10.240Z thumbsup:error     at stream.write (/usr/local/lib/node_modules/thumbsup/node_modules/event-stream/index.js:61:10)
2024-06-12T01:15:10.240Z thumbsup:error     at Stream.ondata (node:internal/streams/legacy:20:31)
2024-06-12T01:15:10.240Z thumbsup:error     at Stream.emit (node:events:512:28)
2024-06-12T01:15:10.240Z thumbsup:error     at Stream.reemit (/usr/local/lib/node_modules/thumbsup/node_modules/duplexer/index.js:70:25)
2024-06-12T01:15:10.240Z thumbsup:error     at Stream.emit (node:events:512:28)
2024-06-12T01:15:10.240Z thumbsup:error     at drain (/usr/local/lib/node_modules/thumbsup/node_modules/through/index.js:36:16)
2024-06-12T01:15:10.240Z thumbsup:error     at stream.queue.stream.push (/usr/local/lib/node_modules/thumbsup/node_modules/through/index.js:45:5)
2024-06-12T01:15:10.240Z thumbsup:error     at parser.onValue (/usr/local/lib/node_modules/thumbsup/node_modules/JSONStream/index.js:118:16)
```

This is on Ubuntu on WSL2 on Windows 11.

**Comment by inhahe** [comment]
I'm running it with --log trace right now..

**Comment by inhahe** [comment]
I couldn't tell from --log trace which file it crashed on or which directory it was in.

**Comment by inhahe** [comment]
But I can tell you it was reading a Windows directory under `/mnt`.

**Comment by inhahe** [comment]
I just got the same error on Mint Cinnamon (again reading a Windows directory, this time shared by VirtualBox)

**Comment by inhahe** [comment]
I just copied the Windows directory to a local Linux directory and ran thumbsup on that and still got the error.

**Comment by inhahe** [comment]
I  tried `find ./picsdir -type f -exec touch -m {} +` to change the last modified date of every file in the directory and re-ran thumbsup, and I still got the error.

**Comment by inhahe** [comment]
I just ran detox on all the files, and now I don't get that error. I realized that I've already reported this error before and it was mostly fixed but apparently there's a corner case in this directory structure.

But now that I'm no longer getting the file error I'm getting 1 albums, 0 photos, 0 videos     │

**Comment by inhahe** [comment]
I just ran detox on all the files, and now I don't get that error. I just realized that I've already reported this error before and it was mostly fixed but apparently there's a corner case in this directory structure.
