### ISSUE TITLE
path argument must be a string

### ISSUE THREAD

**Issue by eephyne** [thumbsup/thumbsup#78]
## Bug report

If running as an npm package:

```
Thumbsup version: 2.2.0 alpha 1
Node version: v9.2.0
NPM version: 5.5.1
Operating system: Arch linux 64bit
```

About the bug...
I tried running thumbsup in a simple folder with one subfolder to check if its working and it was (there was no video).
But when I run it in my real photo album folder, after two days of running ffmpeg, it crash during the webpage creations. Considering the message I assume its because of a pathname but I can't get more info and I'm not familiar with node.
I did run it with DEBUG="*" in the quote below
```

Creating albums     [=========================] done
Building website    [-------------------------] path.js:28
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
    ^


TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.relative (path.js:1265:5)
    at Media.<anonymous> (/usr/lib/node_modules/thumbsup/src/output-website/template.js:101:17)
    at eval (eval at createFunctionContext (/usr/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:109)
    at Object.prog [as fn] (/usr/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at Album.<anonymous> (/usr/lib/node_modules/thumbsup/src/output-website/template.js:48:20)
    at eval (eval at createFunctionContext (/usr/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:16:72)
    at prog (/usr/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at execIteration (/usr/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/usr/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)

```

**Comment by rprieto** [comment]
Thanks a lot for the bug report! I’ll investigate now and see what I can find.

Out of curiosity how many photos/videos are in the folder? It won’t be related to the issue but 2 days of ffmpeg sounded like a lot.

**Comment by rprieto** [comment]
Would you be comfortable making a small change (that I give you) to a `.js` file to add more debugging information?

**Comment by zbacsi** [comment]
I've got the same error too. There are 896 image, 49 video file in this folder. I'd like to try that little change on that js file.

**Comment by rprieto** [comment]
Sorry about that. It's quite likely that it's a change in the latest `2.2.0-alpha.1` version. It seems that `npm` downloads this as a default even though it's an alpha, I'll check how to prevent that.

The weird thing is that the following path in error doesn't exist anymore, that was from an old version:

```bash
at Media.<anonymous> (/usr/lib/node_modules/thumbsup/src/output-website/template.js:101:17)
```

@zbacsi can you confirm which path you're seeing in the error stack trace?

**Comment by eephyne** [comment]
About 8000 pictures and 900 videos.
I just downgraded but I still got the same error. In fact I think I did misread the npm view information, I should instead use list and I think I always got the 2.1.0, sorry for that.
I precise also that the package is installed as root (if that could be useful in any ways).

By the way, I do not mind at all modifying the content of a file (in fact I already was doing some console.log to check , but did'nt get any info so far, like I said, not used to node)

**Comment by zbacsi** [comment]
```
Finding media       [=========================] 945/945 done
Updating database   [=========================] up to date
Processing photos   [=========================] up to date
Processing videos   [=========================] up to date
Creating albums     [=========================] done
Building website    [-------------------------] path.js:28
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.relative (path.js:1265:5)
    at Media.<anonymous> (/usr/local/lib/node_modules/thumbsup/src/output-website/template.js:101:17)
    at eval (eval at createFunctionContext (/usr/local/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:74)
    at Object.prog [as inverse] (/usr/local/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at Media.<anonymous> (/usr/local/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:17:22)
    at eval (eval at createFunctionContext (/usr/local/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:35)
    at prog (/usr/local/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at execIteration (/usr/local/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
```

**Comment by rprieto** [comment]
Nice @eephyne, that's the same size as one of the galleries I update weekly. Should work really well.

Thanks for confirming the version, and thanks @zbacsi for the stack trace too. I'll have a look now and hopefully have a fix soon!

**Comment by eephyne** [comment]
I got this

`Building website    [-------------------------] current . target undefined`

**Comment by rprieto** [comment]
Thanks! Which theme are you using? Does it also crash if you switch themes? (e.g. `--theme cards` or `--theme mosaic`)

**Comment by zbacsi** [comment]
It crashes with and without theme. Seems target is undefined. I tried --albums-output-folder option too, but no success.

**Comment by rprieto** [comment]
That's the piece of code responsible for rendering the images and links in the HTML pages. It looks like it does't know the path to one of the thumbnails. I'll keep searching and let you know. Long shot, but can you think of any file that's different in your folder? Maybe a weird extension for example?

Also, was thumbsup working for you before or is that the first try?

**Comment by rprieto** [comment]
Would you mind making 1 other change, in `template.js` line 105:

```js
    render: function (template, data, folder) {
      console.log('template', template, 'album', data.album.title)
      // then the rest untouched
    }
```

**Comment by zbacsi** [comment]
Intresting, it works:

```
$ thumbsup --input teszthost/www/shared/2016/2016.03.25.tihany_husvet/ --output www/2016.03.25

Finding media       [=========================] 288/288 done
Updating database   [=========================] up to date
Processing photos   [=========================] up to date
Processing videos   [=========================] up to date
Creating albums     [=========================] done
Building website    [-------------------------] template album album Home
Building website    [=========================] done

Gallery generated successfully
```

But:

```
$ thumbsup --input teszthost/www/shared/2012 --output www/gallery/2012/

Finding media       [=========================] 945/945 done
Updating database   [=========================] up to date
Processing photos   [=========================] up to date
Processing videos   [=========================] up to date
Creating albums     [=========================] done
Building website    [-------------------------] template album album Home
path.js:28
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.relative (path.js:1265:5)
    at Media.<anonymous> (/usr/local/lib/node_modules/thumbsup/src/output-website/template.js:101:17)
    at eval (eval at createFunctionContext (/usr/local/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:74)
    at Object.prog [as inverse] (/usr/local/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at Media.<anonymous> (/usr/local/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:17:22)
    at eval (eval at createFunctionContext (/usr/local/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:35)
    at prog (/usr/local/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at execIteration (/usr/local/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
```

There is no difference in the console.log output: template album album Home

**Comment by zbacsi** [comment]
It works for me when I run it from the target directory.

**Comment by zbacsi** [comment]
There are only jpg and mp4 files in the source folder. The thumbnails are generated successfully. There are no weird extensions, no spaces in the filenames.

**Comment by rprieto** [comment]
Thanks. While I keep looking the only thing I can think of is to binary search `templates/themes/classic/theme.hbs`  to see which part of the template is crashing. For example deleting 1/2 of the file (e.g. the whole video section) and seeing if the crash is gone.

Thanks for your patience and your help troubleshooting this. Hopefully it's something obvious we can fix straight away.

**Comment by eephyne** [comment]
I isolated the issue to one folder, they all seems normal in there , I investigate more and post here if I found anything

**Comment by rprieto** [comment]
Thanks a lot for that! I’ll make sure to add tests around this case once fixed.

**Comment by eephyne** [comment]
well I finally found out, it seem to be a empty image file. 

```
http@playbox /srv/http % ls -l orig
total 0
-rw-r--r-- 1 http http 0 28 nov.  08:10 20110928_174256.PIC_0050.jpg
http@playbox /srv/http % thumbsup --input ./orig --output ./test_thumbsup

Finding media       [=========================] 1/1 done
Updating database   [=========================] up to date
Processing photos   [=========================] up to date
Processing videos   [=========================] up to date
Creating albums     [=========================] done
Building website    [-------------------------] current . target undefined
path.js:28
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.relative (path.js:1265:5)
    at Media.<anonymous> (/usr/lib/node_modules/thumbsup/src/output-website/template.js:107:17)
    at eval (eval at createFunctionContext (/usr/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:74)
    at Object.prog [as inverse] (/usr/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at Media.<anonymous> (/usr/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:17:22)
    at eval (eval at createFunctionContext (/usr/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:35)
    at prog (/usr/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at execIteration (/usr/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/usr/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)

```

**Comment by rprieto** [comment]
Thanks! I had a look at the code and the crash makes sense. What do you think should be the behaviour?

- render the file in the album, with a special icon to show its broken
- skip it, but print a warning at the end

This should probably match the behaviour for #75.

**Comment by eephyne** [comment]
oups juste posted a comment in the same time as you.
I don't know, considering that empty files is an error in the first place in pictures directory I think ignoring it and showing a warning is better

**Comment by rprieto** [comment]
That sounds good. For now I'll push a quick change to skip it, and later add a warning with all files that were skipped.

**Comment by rprieto** [comment]
Thanks again for all your help troubleshooting! I'll release `v2.2.0` soon which will include this fix.

**Comment by rprieto** [comment]
Can you please try version `npm install -g thumbsup@2.2.0-alpha.2`?

**Comment by eephyne** [comment]
I don't know if this is related to me or the git repo but I can't install
version of thumbsup depending of git cloning. Always got a permission
denied even if the folder is rwx for everyone.

2017-11-28 22:44 GMT+01:00 Romain <notifications@github.com>:

**Comment by zbacsi** [comment]
It works with 2.2.0-alpha.2 with the same input folder:
```
$ thumbsup --input teszthost/www/shared/2012 --output www/gallery/2012/ 

 ✔ Indexing folder
 ✔ Resizing media
 ✔ Creating website

 Gallery generated successfully
 0 albums, 895 photos, 49 videos
```
But when I try to add the --albums-from date switch, it fails:
```
$ thumbsup --input teszthost/www/shared/2012 --output www/gallery/2012/ --albums-from date

 ✔ Indexing folder
 ✔ Resizing media
 ⠙ Creating website
path.js:28
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.relative (path.js:1265:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/thumbsup/src/website/template.js:50:17)
    at eval (eval at createFunctionContext (/usr/local/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:8:89)
    at Object.prog [as fn] (/usr/local/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/runtime.js:221:12)
    at Object.module.exports (/usr/local/lib/node_modules/thumbsup/src/website/helpers/compare.js:37:20)
    at Object.eval [as main] (eval at createFunctionContext (/usr/local/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:12:76)
    at main (/usr/local/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/runtime.js:175:32)
    at ret (/usr/local/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/runtime.js:178:12)
    at ret (/usr/local/lib/node_modules/thumbsup/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:526:21)
```

Can you tell me where is path.js?

**Comment by eephyne** [comment]
path.js is a node file not a thumbsup file ,it throw error because the template.js send him a wrong object

**Comment by rprieto** [comment]
Sorry about that 😖  There was another small issue which is now fixed on master. On the bright side, more unit tests now.

```bash
npm install -g git+https://github.com/thumbsup/thumbsup.git
```

**Comment by eephyne** [comment]
same with git path, I think this is related to my installation but its killing me…

**Comment by rprieto** [comment]
That's weird. What kind of errors do you get? Just published `2.2.0-alpha.3`.

**Comment by eephyne** [comment]
```
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/thumbsup/listr-work-queue.git /root/.npm/_cacache/tmp/git-clone-b362cb72
npm ERR! fatal: impossible de créer les répertoires de premier niveau dans '/root/.npm/_cacache/tmp/git-clone-b362cb72': Permission non accordée
npm ERR! 

```

**Comment by rprieto** [comment]
Looks like the `.npm` cache is owned by root, that's odd.

**Comment by eephyne** [comment]
Thats what I thought even if I was running it with sudo, I tried giving all the right to the folder but the same apply, changing the cache folder, same, running it as root directly, same…

**Comment by zbacsi** [comment]
I know there are more workarounds for npm -g permission issues, this one worked for me:
```
sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
```

**Comment by eephyne** [comment]
yeah finally !
Its working for me too, I tested it on my test folder with only empty picture and no error throw.
Nice job :p

**Comment by rprieto** [comment]
Glad it's working! Thanks again for the troubleshooting.
